### ISSUE TITLE
CrossOver Error (`setBadge`) | PLEASE UPDATE TO THE LATEST VERSION

### ISSUE THREAD

**Issue by Sykunae** [lacymorrow/crossover#153]
---
	
	TypeError: windows.setBadge is not a function:
	TypeError: windows.setBadge is not a function
    at NsisUpdater.<anonymous> (C:\Users\hrvoj\AppData\Local\Temp\27UaVUQfGUYgaOqe4G5VUkyhLMU\resources\app.asar\src\main\auto-update.js:59:13)
    at NsisUpdater.emit (events.js:315:20)
    at NsisUpdater.dispatchUpdateDownloaded (C:\Users\hrvoj\AppData\Local\Temp\27UaVUQfGUYgaOqe4G5VUkyhLMU\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:581:10)
    at Object.done (C:\Users\hrvoj\AppData\Local\Temp\27UaVUQfGUYgaOqe4G5VUkyhLMU\resources\app.asar\node_modules\electron-updater\out\BaseUpdater.js:42:14)
    at done (C:\Users\hrvoj\AppData\Local\Temp\27UaVUQfGUYgaOqe4G5VUkyhLMU\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:719:25)
    at async NsisUpdater.executeDownload (C:\Users\hrvoj\AppData\Local\Temp\27UaVUQfGUYgaOqe4G5VUkyhLMU\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:757:12)

	---

	CrossOver 3.0.0-4
Electron 11.5.0
win32 10.0.19044
Locale: en-US

**Comment by lacymorrow** [comment]
CrossOver 3.0.0-4 had some errors, can you try v3?
https://github.com/lacymorrow/crossover/releases

**Comment by lacymorrow** [comment]
I'm really sorry about this, I believe I pushed a bug in version 2.7.4 that actually broke the auto-updater. 

The fix is to manually install v3.0.0: https://github.com/lacymorrow/crossover/releases/tag/v3.0.0

**Comment by lacymorrow** [comment]
duplicate #153 #154 #155  #156

**Comment by nomis51** [comment]
Still happening to me in version 3.1.
Did a full clean (uninstalled manually the other version 2.7.4, remove anything remaining in app data).
First start is fine, on the second one it starts happening endlessly again.

I saw it's a bug coming from 2.7.4 that got into 3.0 "beta", but still happen to me in 3.1.

**Comment by lacymorrow** [comment]
@nomis51 do you remember what the error you received was? I’m working on this now, it’s due to the windows store build

**Comment by nomis51** [comment]
> @nomis51 do you remember what the error you received was? I’m working on this now, it’s due to the windows store build

it's the setBadge one, here the stack trace 
```Unhandled Promise Rejection
TypeError: Cannot read property 'setBadge' of undefined
    at Object.setBadge (C:/Users/me/AppData/Local/Programs/crossover/resources/app.asar/src/main/dock.js:5:35)
    at NsisUpdater.onUpdateDownloaded (C:/Users/me/AppData/Local/Programs/crossover/resources/app.asar/src/main/auto-update.js:51:7)
    at NsisUpdater.dispatchUpdateDownloaded (C:/Users/me/AppData/Local/Programs/crossover/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:581:10)
    at Object.done (C:/Users/me/AppData/Local/Programs/crossover/resources/app.asar/node_modules/electron-updater/out/BaseUpdater.js:42:14)
    at done (C:/Users/me/AppData/Local/Programs/crossover/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:719:25)
    at async NsisUpdater.executeDownload (C:/Users/me/AppData/Local/Programs/crossover/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:730:14)```

**Comment by lacymorrow** [comment]
I've updated things and added fixes in v3.1.5, check out https://github.com/lacymorrow/crossover/releases/latest

**Comment by nomis51** [comment]
> I've updated things and added fixes in v3.1.5, check out https://github.com/lacymorrow/crossover/releases/latest

Works perfectly!

**Comment by lacymorrow** [comment]
THANK YOU for testing it out, I really appreciate your help @nomis51

**Comment by lacymorrow** [comment]
Duplicates: #189, #187

**Comment by lacymorrow** [comment]
📋 Reviewed by Paperclip — categorized as discussion/community thread/wontfix. No task created.

**Comment by lacymorrow** [comment]
📋 Tracked in Paperclip as **LAC-1796**. This issue has been added to our internal project management system and will be reviewed by the engineering team.

**Comment by lacymorrow** [comment]
Tracked in Paperclip as **LAC-2585**. This issue has been added to our internal project management system and will be reviewed by the engineering team.

**Comment by lacymorrow** [comment]
The setBadge error was a version-specific Electron bug that's been fixed in subsequent releases. If you're still seeing this, make sure you're on the latest CrossOver version.
