### ISSUE TITLE
Constant error

### ISSUE THREAD

**Issue by xMealsOnWheels** [lacymorrow/crossover#310]
I had crossover installed and it asked me to update it. So i did. It then came up with this error. This error occurs every time I open Crossover and will randomly occur while gaming. Uninstalling and reinstalling has not fixed the error occurring.

	---
	
	TypeError: Cannot read property 'setBadge' of undefined:
	TypeError: Cannot read property 'setBadge' of undefined
    at Object.setBadge (C:\Users\xK-la\AppData\Local\Programs\crossover\resources\app.asar\src\main\dock.js:5:35)
    at NsisUpdater.<anonymous> (C:\Users\xK-la\AppData\Local\Programs\crossover\resources\app.asar\src\main\auto-update.js:60:10)
    at NsisUpdater.emit (events.js:315:20)
    at NsisUpdater.dispatchUpdateDownloaded (C:\Users\xK-la\AppData\Local\Programs\crossover\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:581:10)
    at Object.done (C:\Users\xK-la\AppData\Local\Programs\crossover\resources\app.asar\node_modules\electron-updater\out\BaseUpdater.js:42:14)
    at done (C:\Users\xK-la\AppData\Local\Programs\crossover\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:719:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async NsisUpdater.executeDownload (C:\Users\xK-la\AppData\Local\Programs\crossover\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:730:14)

	---

	CrossOver 3.0.0
Electron 11.5.0
win32 10.0.22631
Locale: en-US

**Comment by xMealsOnWheels** [comment]
I realised that the version that I was manually installing (due to the app not updating correctly) was the old version. Updated to the new version and the issue is now fixed.

**Comment by lacymorrow** [comment]
Once again, I am so so sorry for you having to deal with this problem. Auto updates are tricky and I really screwed the pooch on this one. Three years later and people are still having problems.

 The new version should be fine. I’ll try to test my updates more before push out but I’m a one-man band.

**Comment by xMealsOnWheels** [comment]
You’re doing a great job! Don’t beat yourself up about it. You’re only human! I love the app!
